### ISSUE TITLE
Creative notches off & glitched

### ISSUE THREAD

**Issue by fineless71** [dracula/minecraft#10]
The notches in the creative menu are off and some are cut off & glitched. I'm on 1.7.10.
![2023-10-15_15 13 43](https://github.com/dracula/minecraft/assets/118756680/73ddc00a-4545-438d-844f-b0ad235c395d)

**Comment by fineless71** [comment]
#6 but for 1.7.10

**Comment by fineless71** [comment]
Also creative related, the slots are wrong:
![2023-10-15_15 35 27](https://github.com/dracula/minecraft/assets/118756680/4fb72769-9946-4b8d-9e08-455f168012cc)

**Comment by Zentheon** [comment]
Somehow I mixed up the 1.19.3 tab change again in Beta1, though it's already fixed internally and I'll ideally have it out today or tomorrow

**Comment by Zentheon** [comment]
Fixed as of Beta2

**Comment by fineless71** [comment]
Fixed but the rail and sword look a bit too close to the edges. Maybe the notches could be made bigger?
![image](https://github.com/dracula/minecraft/assets/118756680/3692ed03-fd05-4ce5-97bc-85a303ea8635)

**Comment by Zentheon** [comment]
Currently working on final revisions for a lot of textures so I'll look into it
