### ISSUE TITLE
Crosshair & other textures getting mixed

### ISSUE THREAD

**Issue by fineless71** [dracula/minecraft#11]
There's a little bit under the crosshair. I'm on 1.7.10
![image](https://github.com/dracula/minecraft/assets/118756680/e0ebfd84-5a02-4d8c-bcd0-e401ac338379)

**Comment by Zentheon** [comment]
Will check this one out when I'm back home. Thanks for all the reports by the way!

**Comment by Zentheon** [comment]
Fixed as of Beta2
