### ISSUE TITLE
Villager UI needs a fix

### ISSUE THREAD

**Issue by Carmassi** [dracula/minecraft#12]
My minecraft version is 1.20.2 (but this UI problem is from the updated villager UI from 1.14 update)
First i used the 1.20.2 version of the resourcepack but it was bugged and then i tried the 1.21 version but it's the same :(

Other resourcepacks seems to work so i don't think the problem are from my client mods (i'm using sodium, carpetmod and others like that but nothing changes any UI)

![image](https://github.com/dracula/minecraft/assets/67022366/4b2d3ca8-cd64-471c-afb3-fc12e3878903)

![image](https://github.com/dracula/minecraft/assets/67022366/7d275c30-b0f5-43bf-96a4-6bcecd74fbdc)

![image](https://github.com/dracula/minecraft/assets/67022366/c81af235-63ed-4be8-9a99-33ce02dfd4a0)

**Comment by Zentheon** [comment]
That's definitely a problem with the pack! I forgot there was a name change with the villager UI in 1.20.2. Will put that on the todo

**Comment by Zentheon** [comment]
Fixed as of Beta 3!

**Comment by fineless71** [comment]
Also messed up on 1.7.10 (I'm using beta 3)
![image](https://github.com/dracula/minecraft/assets/118756680/181c2a3e-98ba-40e6-808d-98a1fe3bc0da)

**Comment by Zentheon** [comment]
Reopening this. Surely one day I'll get the villagers figured out for good
