### ISSUE TITLE
update

### ISSUE THREAD

**Issue by Momcube** [dracula/minecraft#15]
Please update to 1.20.4 this is my all-time favorite resource pack!
thank you!

**Comment by Zentheon** [comment]
Hey there! Sorry I'm a bit late, got hit with a super fun flu episode. Anyway, the 1.20.2 version should still work fine on the latest update, just have to skip the outdated pack warning.

Appreciate the comment though! Going to try getting back to working on better mod support for another update!

**Comment by Momcube** [comment]
i hope you feel better! and no ive tired it doesnt work :/ the Dracula Theme Hybrid one doesnt work but the Dracula Theme does but im dying to have the Hybrid one updated when you have a chance! thank you for writing back!

**Comment by Zentheon** [comment]
Ahhh okay, I had kinda forgotten Hybrid existed haha. I'll have to get around to it at some point, but no guarantees on when since these projects are not easy to keep up with.
