### ISSUE TITLE
[b1.7.3] Half armor on wrong side

### ISSUE THREAD

**Issue by fineless71** [dracula/minecraft#16]
For some reason I can't find where I got this mc version of the pack from. Was it taken down or am I just crazy? It's also not the latest version of the pack so if it's been fixed lmk (I would update, but again I can't find it :p)

![image](https://github.com/dracula/minecraft/assets/118756680/af393fcd-1241-4f76-85b7-f2f3cd873cf7)

## The actual issue

In beta 1.7.3, the armor goes from right to left, so the half armor needs to be on the other side. Here's a screenshot from Dracula:
![image](https://github.com/dracula/minecraft/assets/118756680/8420ef2e-80ae-488d-b7e9-153312524293)

And here is one from the Faithful pack: (to show how it should look)
![image](https://github.com/dracula/minecraft/assets/118756680/a9ec6096-f5e2-4e18-b6d0-bbbf9ce7a748)

**If this mc version is no longer maintained, then no worries, you can just close this :slightly_smiling_face:**

**Comment by Zentheon** [comment]
Hey there! That version may have come from some old Curse release, as there've been some pretty major changes since then. There're still some technical problems in the most recent ones, which are currently only up here on Github releases, as well as [Modrinth](https://modrinth.com/resourcepack/dracula-theme/versions).

iirc this particular issue shouldn't exist in the betas but I'm not positive haha

**Comment by fineless71** [comment]
> Hey there! That version may have come from some old Curse release, as there've been some pretty major changes since then. There're still some technical problems in the most recent ones, which are currently only up here on Github releases, as well as [Modrinth](https://modrinth.com/resourcepack/dracula-theme/versions).
> 
> iirc this particular issue shouldn't exist in the betas but I'm not positive haha

Hmm, could you link to the latest version that supports b1.7.3? The oldest I see listed on Modrinth is for r1.6.1, and I checked the `genscript.sh` and that seems to match. I just realized that the version I have is from the `master` branch of this repo, I probably got it from there. I think there was a misunderstanding, I was talking about _Minecraft beta 1.7.3_, not _Minecraft release 1.7.3_ or any version of the pack (except when I said my version might be outdated :p). After taking a look, I don't think the latest versions of this pack (`dev-main` branch) support MC beta versions, so maybe this should be a feature request for support? :) But if you don't want to support these old versions, that's fine too

**Comment by fineless71** [comment]
Oh and if you do want to support old versions, the main "old" versions people play on is `r1.5.2` (almost there!), `r1.2.5`, and `b1.7.3` (mainly `b1.7.3`). Faithful does officially support `b1.7.3` but doesn't do versions in between (eg. they don't have a `b1.8` version of their pack), so you wouldn't need to support a bunch new versions (although it might be similar to such, as much has probably changed..) And yes, there are servers for these versions with players online :slightly_smiling_face: 

_Also versions `a1.1.2_01` and `c0.30-c` but those require jarmods and I don't want to scare you off too much, so ignore those :) (and most people use ClassiCube for classic versions I believe)_

**Comment by Zentheon** [comment]
Ahhhh okay, yeah, I didn't notice you meant the betas. If I remember correctly, it was actually a pull request someone made to add support for pre-resourcepack versions, and even then the betas weren't weant to be supported.

With how limited the old texturepack format is, dark themed resourcepacks in general don't really work. That combined with the different asset structure, it's not something I'm interested in messing with, but if anyone wants to try modifying the old pull request for it, go crazy
