### ISSUE TITLE
Resource reload failed

### ISSUE THREAD

**Issue by sandenbergmelo** [dracula/minecraft#17]
I'm getting this error when trying to activate the resource pack
I'm in Minecraft 1.20.6 and using the pack in version V2.0 Beta 3 to 1.20.3 with GUI scale 3
Please update the resource to new versions and fix this error

![image](https://github.com/dracula/minecraft/assets/77549672/0c2a18a6-25cd-4f1e-9af4-c5458d7079a8)

**Comment by Zentheon** [comment]
There were some changes to the way fonts work which is what throws the error. For now, here are a couple packs that will just use the legacy font version instead (ignore old pack warning)

### Scale 3
[Dracula v2.0 B3 GUI Scale 3 MC 1.20.2.zip](https://github.com/dracula/minecraft/files/15381028/Dracula.v2.0.B3.GUI.Scale.3.MC.1.20.2.zip)
### Scale 4
[Dracula v2.0 B3 GUI Scale 4 MC 1.20.2.zip](https://github.com/dracula/minecraft/files/15381030/Dracula.v2.0.B3.GUI.Scale.4.MC.1.20.2.zip)

**Comment by Zentheon** [comment]
Fixed as of Beta4!
