### ISSUE TITLE
[Bug] Minecraft logo display is broken (1.20/GUI Scale 3)

### ISSUE THREAD

**Issue by EDM115** [dracula/minecraft#7]
Happens on :
- v1.20.1
- have fabric modloader (probably unrelated) in its latest version
- dracula theme v2 alpha 1
- GUI scale 3

![huge_2023-09-20_09 02 44](https://github.com/dracula/minecraft/assets/82015596/0f0f3d0b-eec6-42a2-8df8-295c78b08ae4)

**Comment by Zentheon** [comment]
thanks for pointing this out! I haven't been keeping up with Minecraft much lately but it looks like 1.20.2 heavily restructures GUI assets. They also released a tool for automatic conversion which I'll check out now.

**Comment by Zentheon** [comment]
Now fixed as of Beta1 which is out on Modrinth
