### ISSUE TITLE
Obfuscation makes text jitter

### ISSUE THREAD

**Issue by fineless71** [dracula/minecraft#8]
Obfuscated text makes the text after it jitter. In other packs and vanilla, this doesn't happen. I'm playing on 1.7.10 but it probably affects other versions too.

https://github.com/dracula/minecraft/assets/118756680/acedae24-1927-4f33-b624-313a0fb3add2

**Comment by Zentheon** [comment]
Surprised I never noticed this sooner. Likely been an issue for a while because of sizing differences from vanilla. Will fix next update

**Comment by Zentheon** [comment]
I haven't been able to properly test this one but hopefully fixed?

**Comment by fineless71** [comment]
Unfortunately not fixed. You can use the server `bwhub.net`'s MOTD to test quickly if it helps.
![Jitter](https://github.com/dracula/minecraft/assets/118756680/8e2c6266-bfce-4df6-90a1-b5b26ecd1031)

**Comment by Zentheon** [comment]
Reopened. Not entirely sure if this can actually be fixed, but will give it another look at!

**Comment by Zentheon** [comment]
I don't actually recall changing anything but I also can't seem to replicate this anymore either. Is it still a thing? And if so, something like copy/paste book text would help a lot.

**Comment by fineless71** [comment]
Still happening. I'm not sure what you mean by book text, like this?: `§k|§r Example`, you can use more bars to make it more obvious: `§k||||||||||§r Example`
BTW about you not being able to replicate, for some reason using multiple packs seems to randomly pick one of the fonts instead of using the top pack (maybe related to a mod like OptiFine). Try replicating while only using the Dracula pack

**Edit:** I get this bug on 1.7.10 but not on 1.8.9
