### ISSUE TITLE
Unwanted lapis slot

### ISSUE THREAD

**Issue by fineless71** [dracula/minecraft#9]
I'm playing on 1.7.10, where the enchantment table doesn't use lapis. The pack still shows a lapis slot when it shouldn't be there.
![2023-10-15_15 07 43](https://github.com/dracula/minecraft/assets/118756680/1241e4fd-70bb-4fcc-b4f1-8cd88ebe44c1)

**Comment by Zentheon** [comment]
This one totally flew under my radar when transitioning to the revamped graphics. Noted!

**Comment by Zentheon** [comment]
Fixed as of Beta2

**Comment by fineless71** [comment]
It's fixed but I originally downloaded the wrong one as 1.7.10 and 1.8.9 are labelled the exact same on Modrinth (and the 1.8.9 one is shown when filtering for 1.7.10).
![image](https://github.com/dracula/minecraft/assets/118756680/317899fd-2ded-4598-9ec5-891247d3b571)

**Comment by Zentheon** [comment]
> It's fixed but I originally downloaded the wrong one as 1.7.10 and 1.8.9 are labelled the exact same on Modrinth (and the 1.8.9 one is shown when filtering for 1.7.10). ![image](https://user-images.githubusercontent.com/118756680/280547588-317899fd-2ded-4598-9ec5-891247d3b571.png)

Edited compatible version for those two
I had assumed Modrinth went by filename and not pack format for automatically listing compatible versions, even though there are a few breaking changes within format 1... Another reason I have a searing disdain for this system mojank went with
